---
- name: Remove dracute useless interface
  tags:
    - lab
    - undercloud-bootstrap
  file:
    path: /etc/sysconfig/network-scripts/ifcfg-ens3
    state: absent

- name: ensure sshd does not rely on gssapi
  tags:
    - lab
    - undercloud-bootstrap
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^GSSAPIAuthentication yes$'
    replace: 'GSSAPIAuthentication no'
  register: sshd_config

- name: restart sshd upon config change
  tags:
    - lab
    - undercloud-bootstrap
  service:
    name: sshd
    state: restarted

- name: Set selinux to permissive
  tags:
    - lab
    - undercloud-bootstrap
  selinux:
    state: permissive
    policy: targeted
  when:
    - disable_selinux|bool

- name: Persist permissive
  tags:
    - lab
    - undercloud-bootstrap
  when:
    - disable_selinux|bool
  copy:
    dest: /etc/selinux/config
    content: |
      SELINUX=permissive
      SELINUXTYPE=targeted

- name: set hostname properly
  tags:
    - lab
    - undercloud-bootstrap
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ undercloud_hostname }} localhost.{{ domain }} undercloud localhost"
    regexp: '^127\.0\.0\.1'

- name: set up custom repositories
  tags:
    - lab
    - undercloud-bootstrap
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.name }}"
    file: "{{ item.file | default(item.name) }}"
    baseurl: "{{ item.uri }}"
    gpgcheck: "{{ item.gpg |default(omit) }}"
    priority: "{{ item.priority |default(omit) }}"
  loop: "{{ custom_repositories }}"

- name: add static routes for overclouds public endpoints
  tags:
    - lab
    - undercloud-bootstrap
  when:
    - hostvars['builder']['nat_vm_addr'] is defined
  register: set_overcloud_pub_routes
  template:
    dest: /etc/sysconfig/network-scripts/route-eth0
    src: undercloud-static-routes.j2

- name: add static route to the live system if needed
  tags:
    - lab
    - undercloud-bootstrap
  when:
    - set_overcloud_pub_routes is defined
    - set_overcloud_pub_routes is changed
  command: ip ro add 10.20.1.0/24 via {{ hostvars['builder']['nat_vm_addr'].stdout|replace('/24','') }} dev eth0

- name: Inject custom PS1
  tags:
    - lab
    - undercloud-bootstrap
  copy:
    dest: /etc/profile.d/ps1.sh
    content: |
      # Set PS1 to reflect OS version and deploy type
      {% if standalone | default(false) | bool %}
      export PS1='[{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }} - \u@standalone \W]\$ '
      {% else %}
      export PS1='[{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }} - \u@\h \W]\$ '
      {% endif %}
